### ISSUE TITLE
Minerva sometimes doesn't register well-formatted descriptions 

### ISSUE THREAD

**Issue by wendi-yu** [waterloo-rocketry/minerva#32]
Minerva only looks at the next four events in the calendar, so if we have more events than that the 5th+ ones won't be registered properly. Look at ways to fix this - should we increase the cap, or do something different and more clever to figure out what to look at?

**Comment by chrissank** [comment]
Increasing the amount to select is the way to go. Should be a single-character change (https://github.com/waterloo-rocketry/minerva/blob/master/src/scheduled/events.js#L13) change the 4 to a higher number. 8 seems reasonable.

**Comment by QuantumManiac** [comment]
Fixed by #34
